# Generated by Django 3.1.5 on 2021-01-23 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemManager',
            fields=[
                ('systemuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.systemuser')),
                ('organization', models.CharField(max_length=50)),
            ],
            bases=('main_app.systemuser',),
        ),
        migrations.AlterField(
            model_name='systemactivitie',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
