# Generated by Django 3.1.5 on 2021-01-28 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemactivitie',
            name='apply_number',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
