# Generated by Django 3.1.5 on 2021-01-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210123_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='SystemManager',
        ),
    ]
